### PR TITLE
Single Dockerfile.template

### LINKED ISSUE #12: Single Dockerfile.template by using the RESIN_ARCH template variable
It is possible to provide a single `Dockerfile.template` instead of three almost identical files by using `RESIN_ARCH` and modifying the `uname` trick we are using for armv7 and armv6.

### PR DESCRIPTION
**Pull request by majorz**
Mainly this PR consolidates the three Dockerfiles into a single one by introducing an extended version of the `uname` modification. There is a separate shell script file in the `scripts` folder for this purpose, which is invoked from the Dockerfile.

There were a couple of bugs that I fixed as well:
1. A positional argument was needed in the Rust part instead of an option one. This made the application always produce `Hello, world!` output, instead of showing the device type.
1. On first launch the fake application (used for dependency cache purposes) was executed. Fixing this needed removing `target/release/deps/hello-*` as well.

I did some small adjustments in the Dockerfile - moving above some WORKDIR definitions so that following statements were more concise.

I bumped the Rust version to latest.

Fixes #12 

Change-type: patch
Signed-off-by: Zahari Petkov <zahari@balena.io>

### CODE REVIEW

**Comment by cyplo** [comment]
looks good to me, thank you :) will test on rpi and x86 and let you know

**Comment by majorz** [comment]
No changes on the `local-push.rs` scripts were needed although `RESIN_ARCH` is used. No need to substitute this one.

**Comment by majorz** [comment]
Yes, please check, and let me know if you encounter any issues.

**Comment by cyplo** [comment]
Heyo @majorz ! 
This tests okay onx86 and rpi3 :tada:  - we did not test on rpi2 before for the lack of hardware, same problem now.

Quick question - in the logs I'm seeing 
```
[Info]     Starting build for raspi, user gh_cyplo
[Info]     Dashboard link: https://dashboard.resin.io/apps/1277499/devices
[Info]     Building on arm02
[Info]     Pulling previous images for caching purposes...
[Success]  Successfully pulled cache images
[main]     Step 1/27 : ARG rust_revision="1.29.1"
```
- `1.29.1` is the previous version - is this expected ?
Then in the logs much later:
```
curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --revision=${rust_revision}                                                                         
[main]      ---> Running in 279ebc163fe4                                                                                                                                                      
[main]     rustup: gpg available. signatures will be verified                                                                                                                                 
[main]     rustup: downloading manifest for 'stable'                                                                                                                                          
[main]     rustup: downloading toolchain for 'stable'                                                                       
```
it should be `1.29.2` instead of `stable` - it seems to be ignoring the version number altogether maybe ?

I'm not sure if this is introduced by this PR or not so don't worry :) Let me know if you want to take a look into the version problem or shall we merge as is and tackle it independently.

**Comment by majorz** [comment]
@cyplo I checked the earlier commit and indeed the `stable` is picked there as well. Let's handle it in a separate PR.

I tested on RPi 1 and things are working there correctly.

I will merge this one now ;)

**Pull request merged**
